url: https://sammymustafa.github.io # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog
logo: /assets/other_icon.png
title: "sammy mustafa" # name of your site
description: "ai data scientist"
theme: academic-jekyll-theme