menu:
- {name: 'about', url: '/about'}
- {name: 'research', url: '/research'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/sammymustafa'}
- {icon: 'twitter', link: 'https://twitter.com/sammy_mustafa'}
- {icon: 'instagram', link: 'https://instagram.com/sammymustafa'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/sammy-s-mustafa/'}

contacts:
- {name: 'Sammy Mustafa', institution: 'Northwestern University', phone: '(201) 957-4754', email: 'sammymustafa@gmail.com', image: 'assets/img/train.jpeg'}
